export const ADD_NEW_FORM = "ADD_NEW_FORM";
export const TOGGLE_FORM_VISIBILITY = "TOGGLE_FORM_VISIBILITY";
export const DELETE_FORM = "DELETE_FORM";
export const ADD_NEW_FIELD_GROUP = "ADD_NEW_FIELD_GROUP";
export const DELETE_FIELD_GROUP = "DELETE_FIELD_GROUP";
export const ADD_NEW_FIELD = "ADD_NEW_FIELD";
export const DELETE_FIELD = "DELETE_FIELD";
export const EDIT_FIELD = "EDIT_FIELD";
